In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/bls.gov/employment/raw/01.csv", delimiter='\t')
df.head()

,series_id,state,area,year,period,month,value
0,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M12,December,1.1
1,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M11,November,1.1
2,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M10,October,1.1
3,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M09,September,1.1
4,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M08,August,1.1

In [4]:
len(set(df.area))

392

In [5]:
df.rename(columns={'value':'total_workers'}, inplace=True)
df.head()

,series_id,state,area,year,period,month,total_workers
0,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M12,December,1.1
1,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M11,November,1.1
2,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M10,October,1.1
3,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M09,September,1.1
4,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M08,August,1.1

In [ ]:
df.total_workers = df.total_workers * 1000

In [11]:
df.head(3)

,series_id,state,area,year,period,month,total_workers
0,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M12,December,1100.0
1,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M11,November,1100.0
2,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M10,October,1100.0

In [14]:
df.dtypes

series_id         object
state             object
area              object
year               int64
period            object
month             object
total_workers    float64
dtype: object

In [15]:
df.total_workers = df.total_workers.astype("int64")
df.head()

,series_id,state,area,year,period,month,total_workers
0,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M12,December,1100
1,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M11,November,1100
2,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M10,October,1100
3,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M09,September,1100
4,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M08,August,1100

In [16]:
df.describe()

               year  total_workers
count  89376.000000   89376.000000
mean    2016.000000   32653.523306
std        5.477256   57352.965629
min     2007.000000     400.000000
25%     2011.000000    5700.000000
50%     2016.000000   13500.000000
75%     2021.000000   31800.000000
max     2025.000000  642200.000000

In [5]:
df2 = pd.read_csv("../data/bls.gov/employment/processed/01_5yr_perc_change.csv", index_col=0)
df2.head()

,state,area,old_year,new_year,old_number,new_number,perc_change
0,South Carolina,"Spartanburg, SC",2021,2025,37.2,41.0,0.102151
1,South Carolina,"Spartanburg, SC",2016,2020,29.9,37.0,0.237458
2,South Carolina,"Spartanburg, SC",2011,2015,26.4,29.0,0.098485
3,Texas,"Dallas-Fort Worth-Arlington, TX",2021,2025,292.6,307.6,0.051265
4,Texas,"Dallas-Fort Worth-Arlington, TX",2016,2020,266.6,281.5,0.055889